"""add_unread_tracking_to_room_members

Revision ID: ff0ea92d1d20
Revises: b0ce0d5ad254
Create Date: 2026-06-06 15:32:28.345098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff0ea92d1d20'
down_revision: Union[str, Sequence[str], None] = 'b0ce0d5ad254'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room_members', sa.Column('unread_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('room_members', sa.Column('last_read_message_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_room_members_last_read_message_id', 'room_members', 'messages', ['last_read_message_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_room_members_last_read_message_id', 'room_members', type_='foreignkey')
    op.drop_column('room_members', 'last_read_message_id')
    op.drop_column('room_members', 'unread_count')
    # ### end Alembic commands ###
